# Generated by Django 4.0.3 on 2022-06-02 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0003_remove_service_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_details',
            field=models.TextField(null=True, verbose_name='Category Detail'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(null=True, upload_to='Category_images/', verbose_name='Category Photo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=250, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='service',
            name='serv_Img',
            field=models.ImageField(null=True, upload_to='Service_images/', verbose_name='Service Photo'),
        ),
        migrations.AlterField(
            model_name='service',
            name='serv_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='y', to='serviceApp.category', verbose_name='Service Category'),
        ),
        migrations.AlterField(
            model_name='service',
            name='serv_details',
            field=models.TextField(verbose_name='Service Detail'),
        ),
        migrations.AlterField(
            model_name='service',
            name='serv_name',
            field=models.CharField(max_length=250, verbose_name='Service Name'),
        ),
    ]
