# Generated by Django 4.0.3 on 2022-06-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0004_alter_category_cat_details_alter_category_cat_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(blank=True, null=True, upload_to='Category_images/', verbose_name='Category Photo'),
        ),
    ]
