# Generated by Django 4.0.3 on 2022-06-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0006_alter_category_cat_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlidShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slid_image', models.ImageField(null=True, upload_to='slide_show/', verbose_name='slide_show Photo')),
                ('slid_title', models.TextField(null=True, verbose_name='slide_show title')),
            ],
            options={
                'verbose_name': 'SlidShow',
                'verbose_name_plural': 'SlidShows',
            },
        ),
    ]
